### ISSUE TITLE
[BAN] Can't ban user throug user-agent only

### ISSUE THREAD

**Issue by qx57** [crypto-pepe/firewall-executor#10]
When I sent request with next body:

> {
    "target": {
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36"
    },
    "reason": "Ban through User-Agent",
    "ttl": 4294967297
}

I awaited a 204 response, but had a 400 Bad Request without response body

**Comment by stuffy-idler** [comment]
Resolved in #17
