### ISSUE TITLE
[BAN] Too big ttl 400 response without body

### ISSUE THREAD

**Issue by qx57** [crypto-pepe/firewall-executor#11]
On the request **POST /api/bans** when I set ttl equal or bigger than 2^32 like this:

> {
    "target": {
        "ip": "12.34.56.78"
    },
    "reason": "Ban through User-Agent",
    "ttl": 4294967296
}

I get 400 Bad Request response with nothing body

**Comment by stuffy-idler** [comment]
Resolved in #17
