### ISSUE TITLE
Reject requests with unknown request body fields

### ISSUE THREAD

**Issue by stuffy-idler** [crypto-pepe/firewall-executor#19]
Server has to response with bad request error (400) with appropriate body for requests with unknown fields in the request body.
E.g.
```json
{
  "target": {
    "ip": "1.1.1.1",
    "bad": "field"
  },
  "ttl": 1,
  "reason": "bad request"
}
```

**Comment by stuffy-idler** [comment]
@horny-manul is it was done in #17?

**Comment by horny-manul** [comment]
Yes, it was done
