### ISSUE TITLE
[BAN] 400 Bad Request response have no body

### ISSUE THREAD

**Issue by qx57** [crypto-pepe/firewall-executor#8]
When we sent request **POST /bans** with one of next body:

> {
            "target": [{
                "user_agent": "user-agent for array test"
            }],
            "reason": "Ban through IP",
            "ttl": 321
        }

or 

> [
            {
                "target": {
                    "user_agent": "user-agent for array test"
                },
                "reason": "Ban through IP",
                "ttl": 321
            }
        ]

response had no body

**Comment by stuffy-idler** [comment]
Resolved in #17
