### ISSUE TITLE
[BAN] Unexpected response for request with wrong user-agent field

### ISSUE THREAD

**Issue by qx57** [crypto-pepe/firewall-executor#9]
I sent POST /bans request with **user-agen** instead of **user_agent** field:

> {
            "target": {
                "ip": "123.123.123.123",
                "user-agent": "user-agent for array test"
            },
            "reason": "Ban through IP",
            "ttl": 322
        }

but I had 204 Ok response without any warnings or errors. In Redis has been created key which contains ip field only.

**Comment by stuffy-idler** [comment]
Resolved in #17
